dist: trusty
language: go
go:
  - 1.8
env:
  global:
    - POSTGRES_DATABASE=dailyteedeals_test
    - MINIO_ACCESS_KEY=access_key
    - MINIO_SECRET_KEY=secret_key
    - MINIO_BROWSER=off
install:
  - make
  - wget -O ./minio https://dl.minio.io/server/minio/release/linux-amd64/minio
  - chmod +x ./minio
before_script:
  - psql -c 'create database dailyteedeals_test;' -U postgres -h localhost
  - mkdir /tmp/minio && ./minio server --quiet /tmp/minio & disown
script:
  - make lint
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
services:
  - postgresql
addons:
  postgresql: "9.5"