dist: trusty
language: go
go:
  - 1.8
env:
  - POSTGRES_DATABASE=dailyteedeals_test
install: 
  - psql -c 'create database dailyteedeals_test;' -U postgres -h localhost
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
  - make install
script:
  - make lint
  - make test
after_success:
  - gover
  - goveralls -coverprofile=gover.coverprofile
services:
  - postgresql
addons:
  postgresql: "9.5"