dist: trusty
language: go
go:
  - 1.8
install: 
  - cp sqlboiler.travis.toml sqlboiler.toml
  - go get github.com/golang/dep/cmd/dep
  - go get github.com/pressly/goose/cmd/goose
  - dep ensure
  - psql -c 'create database travis_ci_test;' -U postgres -h localhost
  - goose -dir migrations postgres "user=postgres dbname=travis_ci_test sslmode=disable" up
script: go test -cover $(go list ./... | grep -v /vendor/)
services:
  - postgresql
addons:
  postgresql: "9.5"