
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  branch = "master"
  name = "github.com/AlasdairF/Titlecase"

[[constraint]]
  name = "github.com/PuerkitoBio/purell"
  version = "1.1.0"

[[constraint]]
  name = "github.com/caarlos0/env"
  version = "3.0.0"

[[constraint]]
  name = "github.com/disintegration/imaging"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/cache"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/gin-contrib/gzip"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "github.com/go-pg/migrations"
  version = "6.0.2"

[[constraint]]
  name = "github.com/go-pg/pg"
  version = "6.4.14"

[[constraint]]
  name = "github.com/gocraft/work"
  version = "0.5.0"

[[constraint]]
  name = "github.com/minio/minio-go"
  version = "3.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/nbio/st"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/rainycape/unidecode"

[[constraint]]
  branch = "master"
  name = "github.com/sethgrid/pester"

[[constraint]]
  name = "gopkg.in/h2non/gock.v1"
  version = "1.0.6"
