// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Artists", testArtists)
	t.Run("Designs", testDesigns)
	t.Run("GooseDBVersions", testGooseDBVersions)
	t.Run("Products", testProducts)
	t.Run("Sites", testSites)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("Artists", testArtistsDelete)
	t.Run("Designs", testDesignsDelete)
	t.Run("GooseDBVersions", testGooseDBVersionsDelete)
	t.Run("Products", testProductsDelete)
	t.Run("Sites", testSitesDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Artists", testArtistsQueryDeleteAll)
	t.Run("Designs", testDesignsQueryDeleteAll)
	t.Run("GooseDBVersions", testGooseDBVersionsQueryDeleteAll)
	t.Run("Products", testProductsQueryDeleteAll)
	t.Run("Sites", testSitesQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Artists", testArtistsSliceDeleteAll)
	t.Run("Designs", testDesignsSliceDeleteAll)
	t.Run("GooseDBVersions", testGooseDBVersionsSliceDeleteAll)
	t.Run("Products", testProductsSliceDeleteAll)
	t.Run("Sites", testSitesSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Artists", testArtistsExists)
	t.Run("Designs", testDesignsExists)
	t.Run("GooseDBVersions", testGooseDBVersionsExists)
	t.Run("Products", testProductsExists)
	t.Run("Sites", testSitesExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("Artists", testArtistsFind)
	t.Run("Designs", testDesignsFind)
	t.Run("GooseDBVersions", testGooseDBVersionsFind)
	t.Run("Products", testProductsFind)
	t.Run("Sites", testSitesFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("Artists", testArtistsBind)
	t.Run("Designs", testDesignsBind)
	t.Run("GooseDBVersions", testGooseDBVersionsBind)
	t.Run("Products", testProductsBind)
	t.Run("Sites", testSitesBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("Artists", testArtistsOne)
	t.Run("Designs", testDesignsOne)
	t.Run("GooseDBVersions", testGooseDBVersionsOne)
	t.Run("Products", testProductsOne)
	t.Run("Sites", testSitesOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("Artists", testArtistsAll)
	t.Run("Designs", testDesignsAll)
	t.Run("GooseDBVersions", testGooseDBVersionsAll)
	t.Run("Products", testProductsAll)
	t.Run("Sites", testSitesAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("Artists", testArtistsCount)
	t.Run("Designs", testDesignsCount)
	t.Run("GooseDBVersions", testGooseDBVersionsCount)
	t.Run("Products", testProductsCount)
	t.Run("Sites", testSitesCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("Artists", testArtistsHooks)
	t.Run("Designs", testDesignsHooks)
	t.Run("GooseDBVersions", testGooseDBVersionsHooks)
	t.Run("Products", testProductsHooks)
	t.Run("Sites", testSitesHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Artists", testArtistsInsert)
	t.Run("Artists", testArtistsInsertWhitelist)
	t.Run("Designs", testDesignsInsert)
	t.Run("Designs", testDesignsInsertWhitelist)
	t.Run("GooseDBVersions", testGooseDBVersionsInsert)
	t.Run("GooseDBVersions", testGooseDBVersionsInsertWhitelist)
	t.Run("Products", testProductsInsert)
	t.Run("Products", testProductsInsertWhitelist)
	t.Run("Sites", testSitesInsert)
	t.Run("Sites", testSitesInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("DesignToArtistUsingArtist", testDesignToOneArtistUsingArtist)
	t.Run("ProductToDesignUsingDesign", testProductToOneDesignUsingDesign)
	t.Run("ProductToSiteUsingSite", testProductToOneSiteUsingSite)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("ArtistToDesigns", testArtistToManyDesigns)
	t.Run("DesignToProducts", testDesignToManyProducts)
	t.Run("SiteToProducts", testSiteToManyProducts)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("DesignToArtistUsingArtist", testDesignToOneSetOpArtistUsingArtist)
	t.Run("ProductToDesignUsingDesign", testProductToOneSetOpDesignUsingDesign)
	t.Run("ProductToSiteUsingSite", testProductToOneSetOpSiteUsingSite)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("ArtistToDesigns", testArtistToManyAddOpDesigns)
	t.Run("DesignToProducts", testDesignToManyAddOpProducts)
	t.Run("SiteToProducts", testSiteToManyAddOpProducts)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Artists", testArtistsReload)
	t.Run("Designs", testDesignsReload)
	t.Run("GooseDBVersions", testGooseDBVersionsReload)
	t.Run("Products", testProductsReload)
	t.Run("Sites", testSitesReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Artists", testArtistsReloadAll)
	t.Run("Designs", testDesignsReloadAll)
	t.Run("GooseDBVersions", testGooseDBVersionsReloadAll)
	t.Run("Products", testProductsReloadAll)
	t.Run("Sites", testSitesReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Artists", testArtistsSelect)
	t.Run("Designs", testDesignsSelect)
	t.Run("GooseDBVersions", testGooseDBVersionsSelect)
	t.Run("Products", testProductsSelect)
	t.Run("Sites", testSitesSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Artists", testArtistsUpdate)
	t.Run("Designs", testDesignsUpdate)
	t.Run("GooseDBVersions", testGooseDBVersionsUpdate)
	t.Run("Products", testProductsUpdate)
	t.Run("Sites", testSitesUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Artists", testArtistsSliceUpdateAll)
	t.Run("Designs", testDesignsSliceUpdateAll)
	t.Run("GooseDBVersions", testGooseDBVersionsSliceUpdateAll)
	t.Run("Products", testProductsSliceUpdateAll)
	t.Run("Sites", testSitesSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}

func TestUpsert(t *testing.T) {
	t.Run("Artists", testArtistsUpsert)
	t.Run("Designs", testDesignsUpsert)
	t.Run("GooseDBVersions", testGooseDBVersionsUpsert)
	t.Run("Products", testProductsUpsert)
	t.Run("Sites", testSitesUpsert)
	t.Run("Users", testUsersUpsert)
}
